@startuml
 start 
:Регистрация/вход в аккаунт; 
:Подтверждение учетных данных;
repeat :Выбор товаров и добавление в корзину; 
:Проверка наличие на складе; 
if (Товар отсутствует?)  then (Да) 
    :Уведомление о недоступности товара;
if (Выбрать альтернативный товар?) then (Да)
    :Выбор товара из аналогичной категории;  
else  (Нет)
    :Удалить товар из корзины; 
endif
else (Нет) 
break 
endif 
repeat while (Выбор товаров завершен?) is (Нет)
-> Да; 
:Оформление заказа; 
fork
    :Выбор способа оплаты и доставки;  
    :Проверка платежных деталей;
    :Проведение транзакции;
fork again
 :Уведомление о сборе заказа;
 :Комплектация заказа;
end fork 
repeat :Проведение оплаты и подготовка товара;
if (Оплата не прошла?) then (Нет)
    :Генерация счета-фактуры;
    :Отправка уведомления о подтверждении заказа;
else  (Да)
    :Отправка уведомления о проблеме с платежом;
    :Повтор попытки или изменение способа оплаты; 
if (Клиент согласен с решением?) then (Нет)
    :Заказ отменяется; 
    :Возращение средств клиенту;
stop   
else  (Да)
endif
endif
repeat while (Оплата прошла?) is (Нет)
-> Да; 
:Заказ в статусе "Отправлен"; 
repeat :Обновление статуса по мере продвижения;
:Уведомления об изменении статуса;
repeat while (Заказ доставлен?) is (Нет)
-> Да; 
stop 
@endumle